name: CICD

on:
  push:
    branches: [main]

jobs:
  build-event:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Docker image and tag
        run: docker build -t shireesh20/cmpe272-hrportal:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push shireesh20/cmpe272-hrportal:latest
