name: CICD

on:
  push:
    branches: [main]

jobs:
  build-event:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Docker image and tag
        run: docker build -t shireesh20/cmpe272-hrportal:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push shireesh20/cmpe272-hrportal:latest
