name: CICD

on:
  push:
    branches: [main]

jobs:
  build-event:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and tag
        run: docker build -t shireesh20/cmpe272-hrportal:latest .

      - name: Push Docker image to Docker Hub
        run: docker push shireesh20/cmpe272-hrportal:latest
